language: java

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

before_cache:
  # Make the cache stable between builds by removing build output
  - rm -rf $HOME/.m2/repository/cc/shanruifeng

cache:
  directories:
    - $HOME/.m2/repository

script:
  - jdk_switcher use openjdk6
  - mvn clean package
  - jdk_switcher use openjdk7
  - mvn clean package
  - jdk_switcher use oraclejdk7
  - mvn clean package
